### ISSUE TITLE
[异常]java.lang.IllegalStateException: aidl is missing

### ISSUE THREAD

**Issue by Redoteam** [lianhuo/Ganamrs#1]
不知道作者有没有遇到这个问题
网上找到的解决方案：http://www.jianshu.com/p/823a2bf685e0
我自己最终的解决方案：在“config.gradle”中将（ buildToolsVersion       : "26.0.1"）修改为 buildToolsVersion       : "26.0.2"

**Comment by lianhuo** [comment]
额 我没有遇到这个问题 感谢指出和提供解决方法

**Comment by Redoteam** [comment]
我刚刚看了你用的框架MVPArms的config.gradle,这是链接：https://github.com/JessYanCoding/MVPArms/blob/master/config.gradle
