### ISSUE TITLE
Fragment懒加载问题

### ISSUE THREAD

**Issue by lishide** [lianhuo/Ganamrs#2]
按照你的BaseFragment重新封装了，底部tab也用的是`com.roughike.bottombar.BottomBar`，网络请求放在了`onFragmentFirstVisible`方法中，但是并没有实现界面可见时再加载数据，而是进入时三个fragment的网络请求都有调用。

**Comment by lianhuo** [comment]
老哥 什么意思？ 是我的demo没有实现懒加载 还是说第一次加载过后在返回fragment没有刷新数据，还是app启动首页三个fragment都进行加载数据了

**Comment by lishide** [comment]
第一次启动，三个fragment都加载了。

**Comment by lianhuo** [comment]
那就是你没有实现懒加载功能啊 你可以看看我这两个文件 https://github.com/lianhuo/Ganamrs/blob/master/app/src/main/java/com/zhy/ganamrs/app/base/BaseFragment.java   https://github.com/lianhuo/Ganamrs/blob/master/app/src/main/java/com/zhy/ganamrs/mvp/ui/fragment/CategoryFragment.java

**Comment by lianhuo** [comment]
懒加载主要方法就是这个 你自己看看吧
public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);
        //setUserVisibleHint()有可能在fragment的生命周期外被调用
        if (rootView == null) {
            return;
        }
        if (isFirstVisible && isVisibleToUser) {
            onFragmentFirstVisible();
            isFirstVisible = false;
        }
        if (isVisibleToUser) {
            onFragmentVisibleChange(true);
            isFragmentVisible = true;
            return;
        }
        if (isFragmentVisible) {
            isFragmentVisible = false;
            onFragmentVisibleChange(false);
        }
    }

**Comment by lishide** [comment]
就是看的这几个文件，一样的呀。知道懒加载使用了setUserVisibleHint，可是我这边每次进入，三个fragment的生命周期都走了，当前看到的其实只是第一个。

**Comment by lianhuo** [comment]
fragment的生命周期肯定会走啊 只是通过 setUserVisibleHint这个方法来控制这个fragment请不请求数据

**Comment by lishide** [comment]
可是这个方法`onFragmentFirstVisible`也在并未可见时调用了。

**Comment by lianhuo** [comment]
那是你basefragment写的不对啊 你好好看看我的demo 我怎么就行

**Comment by lishide** [comment]
我就是直接用的你的`BaseFragment`,唯一不一样的地方是，你的继承的是RxFragment

**Comment by lianhuo** [comment]
那我也不知道该怎么解决了 你可以加一下 301733278 这个qq群

**Comment by lishide** [comment]
没发现有什么地方不一样。我在这个群里。
